pipeline:
  name: linode-ssh-deployment
  identifier: ssh
  projectIdentifier: finalproject
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: SSH_Deployment
        description: Executes build commands on Linode via SSH
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Pull Codebase
                  identifier: Pull_Codebase
                  spec:
                    shell: Bash
                    executionTarget:
                      host: 172.235.134.162
                      connectorRef: linodessh
                      workingDirectory: /home/adrian
                    source:
                     type: Inline
                      spec:
                        script: |-
                          cd minisys-nxt
                          git pull
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
              - step:
                  type: ShellScript
                  name: Install
                  identifier: Install
                  spec:
                    shell: Bash
                    executionTarget:
                      host: 172.235.134.162
                      connectorRef: linodessh
                      workingDirectory: /home/adrian
                    delegateSelectors:
                      - kubernetes-delegate
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cd minisys-nxt/bin
                          ./install-build-tools.sh
                          ./install-test-tools.sh
                    environmentVariables: []
                    outputVariables: []
                  timeout: 30m
              - step:
                  type: ShellScript
                  name: Build
                  identifier: Build
                  spec:
                    shell: Bash
                    executionTarget:
                      host: 172.235.134.162
                      connectorRef: linodessh
                      workingDirectory: /home/adrian
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cd minisys-nxt

                          ./build-system.sh clean
                          ./build-system.sh build
                          ./build-system.sh stage
                          ./build-system.sh images
                    environmentVariables: []
                    outputVariables: []
                    delegateSelectors:
                      - kubernetes-delegate
                  timeout: 30m
        tags: {}
    - stage:
        name: Deploy
        identifier: Deploy
        description: Executes build commands on Linode via SSH
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: Deploy
                  identifier: Deploy
                  spec:
                    shell: Bash
                    executionTarget:
                      host: 172.235.134.162
                      connectorRef: linodessh
                      workingDirectory: /home/adrian
                    delegateSelectors:
                      - kubernetes-delegate
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cd minisys-nxt
                          ./operate-system.sh start all
                    environmentVariables: []
                    outputVariables: []
                  timeout: 30m
              - step:
                  type: ShellScript
                  name: Test
                  identifier: Test
                  spec:
                    shell: Bash
                    executionTarget:
                      host: 172.235.134.162
                      connectorRef: linodessh
                      workingDirectory: /home/adrian
                    delegateSelectors:
                      - kubernetes-delegate
                    source:
                      type: Inline
                      spec:
                        script: |-
                          cd minisys-nxt
                          ./operate-system.sh test
                    environmentVariables: []
                    outputVariables: []
                  timeout: 2h
        tags: {}
